apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'mysql'
  labels:
    app: 'mysql'
  namespace: 'product-services'
spec:
  type: 'NodePort'
  selector:
    app: 'mysql-db'
  ports:
    - targetPort: 3306
      port: 3306
